name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install vulkan-tools libvulkan-dev vulkan-utility-libraries-dev spirv-tools libglfw3-dev libglm-dev
    - name: Install Clang++-17
      run: wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh && chmod u+x /tmp/llvm.sh && sudo /tmp/llvm.sh 17 && rm /tmp/llvm.sh
    - name: Use update alternatives to provide clang++-17
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 1
    - name: Download Vulkan SDK
      run: |
        curl $(curl "https://vulkan.lunarg.com/sdk/files.json" | python3 -c "
        import sys,json
        data = json.loads(sys.stdin.read())
        nm = lambda data: list(data['linux'].keys())[0]
        print(f\"{'https://sdk.lunarg.com/sdk/download/'}{nm(data)}/linux/{data['linux'][nm(data)]['files'][0]['file_name']}\")
        ") | tar -xJ --strip-components=2 --wildcards "*/x86_64/bin/*"
    - name: Make
      run: make GLSLC="bin/glslc" build_linux
