name: Publish documentation

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install doxygen; sudo npm install moxygen -g; sudo pip3 install mkdocs-material
    - name: Make documentation
      run: make documentation
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/site/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4